local includes = {}

function includes:Init(mod)
    include("scripts/enums")
    include("scripts/customcallbacks")
    include("scripts/saves")
    include("scripts/func")

    local characterPath = "scripts/characters/"
    include(characterPath.."/cain/cain")
    include(characterPath.."/isaac/isaac")

    local isaacPath = "scripts/characters/isaac/"
    include(isaacPath.."items/greend6")
    include(isaacPath.."items/sadcucumber")
    include(isaacPath.."items/hotpotato")
    include(isaacPath.."items/pizzaberry")
    include(isaacPath.."items/spicypepper")
    include(isaacPath.."items/leak")
    include(isaacPath.."items/singlepea")
    include(isaacPath.."items/broccoliman")
    include(isaacPath.."items/ancientcarrot")
    include(isaacPath.."items/tangerine")
    include(isaacPath.."items/4dapple")
    include(isaacPath.."items/confusingpear")
    include(isaacPath.."items/poppedcorn")
    include(isaacPath.."items/watermelon")
    include(isaacPath.."items/radish")
    include(isaacPath.."items/jollymint")
    include(isaacPath.."items/waxgourd")
    include(isaacPath.."items/grass")
    include(isaacPath.."items/keylime")
    include(isaacPath.."items/bananarang")
    include(isaacPath.."items/durian")
    include(isaacPath.."items/theonion")
    --include(isaacPath.."items/billiondollarlime")
    include(isaacPath.."items/pomegrenade")
    include(isaacPath.."items/blueberry")
    include(isaacPath.."items/lemonbattery")
    include(isaacPath.."items/ecofriendlyoptions")
    --include(isaacPath.."items/rosemarybead")
    include(isaacPath.."items/hollyberry")
    include(isaacPath.."items/jerusalemsartichoke")
    include(isaacPath.."items/sweetpotato")
    include(isaacPath.."items/missiletoe")
    include(isaacPath.."items/urielshand")
    include(isaacPath.."items/realyspicypepper")
    include(isaacPath.."items/deviledeggplant")
    include(isaacPath.."items/momschives")
    include(isaacPath.."items/hemoguava")
    include(isaacPath.."items/ricinflask")
    include(isaacPath.."items/bloodyorange")
    include(isaacPath.."items/dragonfruitbombs")
    include(isaacPath.."items/cursedgrapes")
    include(isaacPath.."items/starfruit")
    include(isaacPath.."items/demeter")
    include(isaacPath.."items/dadstobacco")
    include(isaacPath.."items/naturalgift")
    include(isaacPath.."items/yellowberry")
    include(isaacPath.."items/elderberry")
    include(isaacPath.."items/honeyberry")
    include(isaacPath.."items/bearberry")
    include(isaacPath.."items/coffeeberry")
    include(isaacPath.."items/blackcurrant")
    include(isaacPath.."items/redcurrant")
    include(isaacPath.."items/crowberry")
    include(isaacPath.."items/barberry")
    include(isaacPath.."items/kramberry")
    include(isaacPath.."items/clumpofhay")
    include(isaacPath.."items/scallion")
    include(isaacPath.."items/babycarrot")
    include(isaacPath.."items/pyrelantern")
    include(isaacPath.."items/cherryontop")
    include(isaacPath.."items/oliveoil")
    include(isaacPath.."items/unicornradish")
    include(isaacPath.."items/jadeberry")
    include(isaacPath.."items/pearry")
    include(isaacPath.."items/grayberry")
    include(isaacPath.."items/fcukberry")

    local cainPath = "scripts/characters/cain/"
    include(cainPath.."machines/oninit")
    include(cainPath.."machines/ondeath")
    include(cainPath.."machines/onupdate")
    include(cainPath.."machines/oncollision")
    include(cainPath.."machine")
    include(cainPath.."greensack")
    include(cainPath.."items/dirtymoney")
    include(cainPath.."items/lessthang")
    include(cainPath.."items/ponderingorb")
    include(cainPath.."items/brotherlylove")
    include(cainPath.."items/satansbet")
    include(cainPath.."items/goldeneye")
    include(cainPath.."items/greenstake")
    include(cainPath.."items/wheeloffortune")

    local jezreelPath = "scripts/characters/jezreel/"
    include(jezreelPath.."jezreel")
    include(jezreelPath.."greenthumb")

    local challengePath = "scripts/challenges/"
    include(challengePath.."biblicallyaccurate")
    include(challengePath.."prologue")

    local entityPath =  "scripts/entities/"

    include(entityPath.."blockbums/abel")
    include(entityPath.."blockbums/seth")
    include(entityPath.."blockbums/basic")
    include(entityPath.."blockbums/devil")
    include(entityPath.."blockbums/key")
    include(entityPath.."blockbums/bomb")
    include(entityPath.."blockbums/battery")
    include(entityPath.."blockbums/rotten")
    include(entityPath.."pickups/greencoin")
    include(entityPath.."pickups/pear")
    include(entityPath.."pickups/potatomagnet")
    include(entityPath.."pickups/sharpstick")
    include(entityPath.."pickups/weirdgummy")
    include(entityPath.."pickups/brokendice")
    include(entityPath.."pickups/glasspenny")
    include(entityPath.."pickups/floweringjade")
    include(entityPath.."greenisaac")
    include(entityPath.."reapprime")
    include(entityPath.."orbglow")

    local itemPath = "scripts/items/"
    include(itemPath.."gunsnroses")
    include(itemPath.."jezreelscurse")
    include(itemPath.."lilsilence")

    include("scripts/commands")

    include("scripts/compat/eid")
    include("scripts/compat/encyclopedia")
    include("scripts/compat/thefuture")

    include("scripts/testrender")
    include("scripts/characters/test")
end

return includes