local mod = jezreelMod

mod.ENUMS = {
    ITEMS = {
        G6 = Isaac.GetItemIdByName("The G6"),
        GREEN_BREAKFAST = Isaac.GetItemIdByName("Green Breakfast"),
        GREEN_SACK = Isaac.GetItemIdByName("Green Sack"),
        GUNS_N_ROSES_REVOLVER = Isaac.GetItemIdByName("Guns n' Roses (REVOLVER)"),
        GUNS_N_ROSES_SHOTGUN = Isaac.GetItemIdByName("Guns n' Roses (SHOTGUN)"),
        GUNS_N_ROSES_NAILGUN = Isaac.GetItemIdByName("Guns n' Roses (NAILGUN)"),
        GUNS_N_ROSES_RAILGUN = Isaac.GetItemIdByName("Guns n' Roses (RAILGUN)"),
        DIRTY_MONEY = Isaac.GetItemIdByName("Dirty Money"), DIRTY_MONEY_DUMMY = Isaac.GetItemIdByName("Dirty Money "),
        PONDERING_ORB = Isaac.GetItemIdByName("Pondering Orb"), PONDERING_ORB_DUMMY = Isaac.GetItemIdByName("Pondering Orb "),
        LESSER_THAN_G = Isaac.GetItemIdByName("G>"), LESSER_THAN_G_DUMMY = Isaac.GetItemIdByName("G> "),
        GREEN_THUMB = Isaac.GetItemIdByName("Green Thumb"),
        BROTHERLY_LOVE = Isaac.GetItemIdByName("Brotherly Love"),
        SATANS_BET = Isaac.GetItemIdByName("Satan's Bet"),
        GOLDEN_EYE = Isaac.GetItemIdByName("Golden Eye"),
        GREEN_STAKE = Isaac.GetItemIdByName("Green Stake"),
        WHEEL_OF_FORTUNE = Isaac.GetItemIdByName("Wheel of Fortune"),
        JEZREELS_CURSE = Isaac.GetItemIdByName("Jezreel's Curse"),
        LIL_SILENCE = Isaac.GetItemIdByName("Lil Silence"),
    },
    VEGETABLES = {
        SAD_CUCUMBER = Isaac.GetItemIdByName("Sad Cucumber"),
        HOT_POTATO = Isaac.GetItemIdByName("Hot Potato"),
        PIZZA_BERRY = Isaac.GetItemIdByName("Pizza Berry"),
        MILDLY_SPICY_PEPPER = Isaac.GetItemIdByName("Mildly Spicy Pepper"),
        LEAK = Isaac.GetItemIdByName("Leak"),
        SINGLE_PEA = Isaac.GetItemIdByName("Single Pea"),
        BROCCOLI_MAN = Isaac.GetItemIdByName("Broccoli Man"),
        ANCIENT_CARROT = Isaac.GetItemIdByName("Ancient Carrot"),
        OBNOXIOUS_TANGERINE = Isaac.GetItemIdByName("Obnoxious Tangerine"),
        FOUR_DIMENSIONAL_APPLE = Isaac.GetItemIdByName("4-Dimensional Apple"),
        CONFUSING_PEAR = Isaac.GetItemIdByName("Confusing Pear"),
        POPPED_CORN = Isaac.GetItemIdByName("Popped Corn"),
        WATERMELON = Isaac.GetItemIdByName("Watermelon"),
        RADISH = Isaac.GetItemIdByName("Radish"),
        JOLLY_MINT = Isaac.GetItemIdByName("Jolly Mint"),
        BEESWAX_GOURD = Isaac.GetItemIdByName("Beeswax Gourd"),
        GRASS_CLIPPINGS = Isaac.GetItemIdByName("Grass Clippings"),
        KEY_LIME = Isaac.GetItemIdByName("Key Lime"),
        BANANARANG = Isaac.GetItemIdByName("Bananarang"),
        SPIKY_DURIAN = Isaac.GetItemIdByName("Spiky Durian"),
        THE_ONION = Isaac.GetItemIdByName("The Onion"),
        --BILLION_DOLLAR_LIME = Isaac.GetItemIdByName("Billion-Dollar Lime"),

        --V2
        POMEGRENADE = Isaac.GetItemIdByName("Pomegrenade"),
        BLUE_BERRY = Isaac.GetItemIdByName("Blue Berry"),
        LEMON_BATTERY = Isaac.GetItemIdByName("Lemon Battery"),
        ECO_FRIENDLY_OPTIONS = Isaac.GetItemIdByName("Eco-Friendly Options"),
        --ROSEMARY_BEAD = Isaac.GetItemIdByName("Rosemary Bead"),
        HOLLY_BERRY = Isaac.GetItemIdByName("Holly Berry"),
        JERUSALEMS_ARTICHOKE = Isaac.GetItemIdByName("Jerusalem's Artichoke"),
        SWEET_POTATO = Isaac.GetItemIdByName("Sweet Potato"),
        MISSILETOE = Isaac.GetItemIdByName("Missiletoe"),
        URIELS_HAND = Isaac.GetItemIdByName("Uriel's Hand"),
        REALLY_SPICY_PEPPER = Isaac.GetItemIdByName("Really Spicy Pepper"),
        DEVILED_EGGPLANT = Isaac.GetItemIdByName("Deviled Eggplant"),
        MOMS_CHIVES = Isaac.GetItemIdByName("Mom's Chives"),
        HEMOGUAVA = Isaac.GetItemIdByName("Hemoguava"),
        RICIN_FLASK = Isaac.GetItemIdByName("Ricin Flask"),
        BLOODY_ORANGE = Isaac.GetItemIdByName("Bloody Orange"),
        DRAGONFRUIT_BOMBS = Isaac.GetItemIdByName("Dragonfruit Bombs"),
        CURSED_GRAPES = Isaac.GetItemIdByName("Cursed Grapes"),
        STARFRUIT = Isaac.GetItemIdByName("Starfruit"),
        DEMETER = Isaac.GetItemIdByName("Demeter"),
        DADS_TOBACCO = Isaac.GetItemIdByName("Dad's Tobacco"),
        NATURAL_GIFT = Isaac.GetItemIdByName("Natural Gift"),
        YELLOWBERRY = Isaac.GetItemIdByName("Yellowberry"),
        ELDERBERRY = Isaac.GetItemIdByName("Elderberry"),
        HONEYBERRY = Isaac.GetItemIdByName("Honeyberry"),
        BEARBERRY = Isaac.GetItemIdByName("Bearberry"),
        COFFEEBERRY = Isaac.GetItemIdByName("Coffeeberry"),
        BLACKCURRANT = Isaac.GetItemIdByName("Blackcurrant"),
        REDCURRANT = Isaac.GetItemIdByName("Redcurrant"),
        CROWBERRY = Isaac.GetItemIdByName("Crowberry"),
        BARBERRY = Isaac.GetItemIdByName("Barberry"),
        KRAM_BERRY = Isaac.GetItemIdByName("Kram Berry"),
        CLUMP_OF_HAY = Isaac.GetItemIdByName("Clump of Hay"),
        SCALLION = Isaac.GetItemIdByName("Scallion"),
        BABY_CARROT = Isaac.GetItemIdByName("Baby Carrot"),
        PYRE_LANTERN = Isaac.GetItemIdByName("Pyre Lantern"),
        CHERRY_ON_TOP = Isaac.GetItemIdByName("Cherry on Top"),
        OLIVE_OIL = Isaac.GetItemIdByName("Olive Oil"),
        UNICORNRADISH = Isaac.GetItemIdByName("Unicornradish"),
        JADEBERRY = Isaac.GetItemIdByName("Jadeberry"),
        PEARRY = Isaac.GetItemIdByName("Pearry"),
        GRAYBERRY = Isaac.GetItemIdByName("Grayberry"),
        FCUKBERRY = Isaac.GetItemIdByName("Fcukberry"),
    },
    VEGETABLES_NUM = {
        [0] = -1,
        [1] = Isaac.GetItemIdByName("Sad Cucumber"),
        [2] = Isaac.GetItemIdByName("Hot Potato"),
        [3] = Isaac.GetItemIdByName("Pizza Berry"),
        [4] = Isaac.GetItemIdByName("Mildly Spicy Pepper"),
        [5] = Isaac.GetItemIdByName("Leak"),
        [6] = Isaac.GetItemIdByName("Single Pea"),
        [7] = Isaac.GetItemIdByName("Broccoli Man"),
        [8] = Isaac.GetItemIdByName("Ancient Carrot"),
        [9] = Isaac.GetItemIdByName("Obnoxious Tangerine"),
        [10] = Isaac.GetItemIdByName("4-Dimensional Apple"),
        [11] = Isaac.GetItemIdByName("Confusing Pear"),
        [12] = Isaac.GetItemIdByName("Popped Corn"),
        [13] = Isaac.GetItemIdByName("Watermelon"),
        [14] = Isaac.GetItemIdByName("Radish"),
        [15] = Isaac.GetItemIdByName("Jolly Mint"),
        [16] = Isaac.GetItemIdByName("Beeswax Gourd"),
        [17] = Isaac.GetItemIdByName("Grass Clippings"),
        [18] = Isaac.GetItemIdByName("Key Lime"),
        [19] = Isaac.GetItemIdByName("Bananarang"),
        [20] = Isaac.GetItemIdByName("Spiky Durian"),
        [21] = Isaac.GetItemIdByName("The Onion"),
    },
}

mod.VEGETABLES = {}
for i=0, #mod.ENUMS.VEGETABLES_NUM do
    mod.VEGETABLES[i]=mod.ENUMS.VEGETABLES_NUM[i]
end